#!/usr/bin/env python3
"""Write the CV's own "Last updated" date into _data/cv.yml.

The homepage shows this date next to the CV download button. It cannot be
taken from the file's timestamp: GitHub Pages re-clones the repository on
every build, so every file ends up stamped with the build time instead.
The date printed inside the PDF is the dependable source.

Run it after replacing assets/Bruce_CV.pdf (the pre-commit hook in
.githooks/pre-commit does this automatically):

    python3 scripts/update-cv-date.py
"""

import datetime
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PDF = ROOT / "assets" / "Bruce_CV.pdf"
OUT = ROOT / "_data" / "cv.yml"

# e.g. "Last updated: Sep 16, 2026" / "Last Updated: September 16, 2026"
DATE_RE = re.compile(r"last\s+updated\s*:?\s*([A-Z][a-z]+\.?\s+\d{1,2},?\s+\d{4})", re.I)


def first_page_text(pdf: pathlib.Path) -> str:
    try:
        from pypdf import PdfReader

        return PdfReader(str(pdf)).pages[0].extract_text() or ""
    except Exception:
        pass
    try:
        return subprocess.run(
            ["pdftotext", "-f", "1", "-l", "1", str(pdf), "-"],
            capture_output=True, text=True, check=True,
        ).stdout
    except Exception:
        return ""


def parse_date(text: str):
    m = DATE_RE.search(text.replace("\n", " "))
    if not m:
        return None
    cleaned = m.group(1).replace(".", "").replace(",", "")
    for fmt in ("%b %d %Y", "%B %d %Y"):
        try:
            return datetime.datetime.strptime(cleaned, fmt).date()
        except ValueError:
            continue
    return None


def main() -> int:
    if not PDF.exists():
        print(f"update-cv-date: {PDF} not found", file=sys.stderr)
        return 1

    date = parse_date(first_page_text(PDF))
    source = "the date printed in the PDF"
    if date is None:
        date = datetime.date.fromtimestamp(PDF.stat().st_mtime)
        source = "the PDF's file timestamp (no date found inside it)"
        print(f"update-cv-date: warning, falling back to {source}", file=sys.stderr)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# Generated by scripts/update-cv-date.py. Do not edit by hand.\n"
        f"# Taken from {source}.\n"
        f'updated: "{date.strftime("%B %Y")}"\n'
        f'updated_full: "{date.strftime("%B %-d, %Y")}"\n',
        encoding="utf-8",
    )
    print(f'update-cv-date: {OUT.relative_to(ROOT)} -> {date.strftime("%B %Y")}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
